### ISSUE TITLE
Computing Standard deviation for 1280 by 328 shows standard deviation = 0 for band 320 to 328

### ISSUE THREAD

**Issue by didierkey** [nasa-jpl/FlightView#1]
It looks like there is bug (I assume in LiveView code or in my camera config) with computing the standard deviation for 1280 by 328: LiveView shows standard deviation = 0 for band 320 to 328. 

Looking at crosshair with LiveView around these bands, there is a variation

I have attached standard deviation display.

I am using:
liveview-master/liveview/lv_release$ ./liveview
/opt/EDTpdv/camera_config/ prism2_328_1280.cfg
![LiveView_CrossHair_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822790-108cb59a-f600-4c46-97e4-0b899dc08304.JPG)
![LiveView_CrossHairZoom_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822791-ebd8c3cd-a633-44f4-ac61-1988192c9fc8.JPG)
![LiveView_Histogram_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822793-39718d6c-88b7-4e99-8ff3-926d3061fe12.JPG)
![LiveView_Raw_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822794-67350140-dd50-4a69-aa20-2d27490fe77c.JPG)
![LiveView_StandardDeviationERR_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822798-7fafcf90-3934-468c-8f30-e778c0a36466.JPG)
![LiveView_StandardDeviationZoomERR_ROIC1280by328_20211213](https://user-images.githubusercontent.com/38109061/148822800-6df03488-a2f6-4596-8d79-320185a1e556.JPG)
![p2_serial_gui_LineDriver_3_254_ROIC1280by328](https://user-images.githubusercontent.com/38109061/148822802-1b82ed7f-49c1-4b8b-82dd-91ad893e2e5e.JPG)
![p2_serial_gui_ROIC1280by328](https://user-images.githubusercontent.com/38109061/148822804-fee5e8d8-f92b-4fd3-a70c-d6a0a798899d.JPG)

**Comment by eliggett** [comment]
Hi Didier, 

- Please try this with the "flightview" branch
- See if `dmesg` on the computer shows any shared memory errors or nvidia driver issues
- If you pan the histogram to the far left side, do you see anything in the "zero" bin?

**Comment by eliggett** [comment]
Also, can you try some other geometries to see if there are missing rows?

**Comment by didierkey** [comment]
> Hi Didier,
>     * Please try this with the "flightview" branch
>     * See if `dmesg` on the computer shows any shared memory errors or nvidia driver issues
>     * If you pan the histogram to the far left side, do you see anything in the "zero" bin?

I have been using on emit02

```
rduce@emit02:/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/LiveViewLegacy$ git status
On branch flightview
Your branch is up to date with 'origin/flightview'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
        modified:   cuda_take/include/mean_filter.hpp
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
        modified:   cuda_take/Makefile
        modified:   liveview.pro
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cuda_take/Makefile-orig
        liveview.pro-orig
rduce@emit02:/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/LiveViewLegacy$ git config -l
etc ...
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/nasa-jpl/LiveViewLegacy.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.flightview.remote=origin
branch.flightview.merge=refs/heads/flightview
submodule.gpsGUI.active=true
submodule.gpsGUI.url=git@github.jpl.nasa.gov:aviris/gpsGUI.git
rduce@emit02:/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/LiveViewLegacy$ pwd
/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/LiveViewLegacy
rduce@emit02:/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/LiveViewLegacy$
```
> Please try this with the "flightview" branch
see the same issues: standard deviation is zero below 320 bands
![image](https://user-images.githubusercontent.com/38109061/149051012-7bc697d6-a181-479f-b039-f8332b3f2849.png)
when zooming to last bands
![image](https://user-images.githubusercontent.com/38109061/149051146-23d0c535-fee5-49fa-9367-f0ccd27309d5.png)
although the value of the pixel is changing along that band
capture time 1
![image](https://user-images.githubusercontent.com/38109061/149051443-95781102-e60f-4a09-a23e-677f0d99ef33.png)
capture time 2
![image](https://user-images.githubusercontent.com/38109061/149051515-1cb61eb6-b0f9-47c7-adfc-74b797e6e086.png)

> See if dmesg on the computer shows any shared memory errors or nvidia driver issues

no message at the console running liveview

```
rduce@emit02:/mnt/DATA1/Applications/LiveView/NasaJPL_github_LiveViewLegacy/branch_flightview/build/lv_release$ ./liveview
test
This version of cuda_take was compiled on Sep 29 2021 at 13:21:09 using gcc 7
The compilation was perfromed by rduce @ emit02
2s compliment filter ENABLED
This version of LiveView was compiled on Sep 29 2021 at 13:26:42 using gcc 7
The compilation was performed by rduce @ emit02
DEBUG MESSAGE IN FLIGHT WIDGET: Starting flight screen widget
WATERFALL: Created specImage with height 1024 and width 1280.
WATERFALL: Finished waterfall constructor.
bool QCPLayoutGrid::addElement(int, int, QCPLayoutElement*) Can't add null element to row/column: 0 -1
DEBUG MESSAGE IN FLIGHT WIDGET: Starting liveview in LAB mode.
DEBUG MESSAGE IN FLIGHT WIDGET: Finished flight constructor.
MainWindow::MainWindow(startupOptionsType, QThread*, frameWorker*, QWidget*) started
x= 2 y= 326
x= 6 y= 323
```

>If you pan the histogram to the far left side, do you see anything in the "zero" bin?
Not really: you should expect 8/328=2% of pixels in zero bin
![image](https://user-images.githubusercontent.com/38109061/149051953-47ef0281-bc1c-4147-966d-0d2d8d808667.png)
 It looks like the histogram is correct. So it may be the display of the standard deviation

> Also, can you try some other geometries to see if there are missing rows?
next test. It requires to modify the ROIC parameters, the LiveView Camera config and programming FPIE-D

**Comment by eliggett** [comment]
This has been fixed in the FlightView branch. The fix was to make sure the allocated thread size is a multiple of the frame geometry (with some constraints). Not only does this fix the missing standard deviation data, but it also increases GPU performance significantly. The fix is in [this commit](https://github.com/nasa-jpl/LiveViewLegacy/commit/1c5dcf6051143efaecb72012c854ada82ce894b7) to the file std_dev_filter.cpp.
